herbs["herbs_long_to_short"] =
{
    ["gruby brazowy grzyb"] = "borowik_krolewski",
    ["grubych brazowych grzybow"] = "borowik_krolewski",
    ["grube brazowe grzyby"] = "borowik_krolewski",
    ["szary kolczasty korzen"] = "aralia",
    ["szarych kolczastych korzeni"] = "aralia",
    ["szare kolczaste korzenie"] = "aralia",
    ["zaostrzony podluzny lisc"] = "szalwia",
    ["zaostrzonych podluznych lisci"] = "szalwia",
    ["zaostrzone podluzne liscie"] = "szalwia",
    ["zlocistopomaranczowy duzy kwiat"] = "arnika",
    ["zlocistopomaranczowych duzych kwiatow"] = "arnika",
    ["zlocistopomaranczowe duze kwiaty"] = "arnika",
    ["rozetkowaty lancetowaty lisc"] = "babka",
    ["rozetkowatych lancetowatych lisci"] = "babka",
    ["rozetkowate lancetowate liscie"] = "babka",
    ["brudnobrazowa cuchnaca galazka"] = "bagno",
    ["brudnobrazowa cuchnaca galazke"] = "bagno",
    ["brudnobrazowych cuchnacych galazek"] = "bagno",
    ["brudnobrazowe cuchnace galazki"] = "bagno",
    ["szarozielony szorstki lisc"] = "boldoa",
    ["szarozielonych szorstkich lisci"] = "boldoa",
    ["szarozielone szorstkie liscie"] = "boldoa",
    ["fioletowy lejkowaty kwiat"] = "barwinka",
    ["fioletowych lejkowatych kwiatow"] = "barwinka",
    ["fioletowe lejkowate kwiaty"] = "barwinka",
    ["jasnobrunatna popekana galazka"] = "bez",
    ["jasnobrunatna popekana galazke"] = "bez",
    ["jasnobrunatnych popekanych galazek"] = "bez",
    ["jasnobrunatne popekane galazki"] = "bez",
    ["duzy bialy kwiat"] = "bielun",
    ["duzych bialych kwiatow"] = "bielun",
    ["duze biale kwiaty"] = "bielun",
    ["czarna blyszczaca fasolka"] = "bobotrutka",
    ["czarna blyszczaca fasolke"] = "bobotrutka",
    ["czarnych blyszczacych fasolek"] = "bobotrutka",
    ["czarne blyszczace fasolki"] = "bobotrutka",
    ["gruby szarawy grzyb"] = "borowik_szatanski",
    ["grubych szarawych grzybow"] = "borowik_szatanski",
    ["grube szarawe grzyby"] = "borowik_szatanski",
    ["wysoki jasnobrazowy grzyb"] = "borowik_szlachetny",
    ["wysokich jasnobrazowych grzybow"] = "borowik_szlachetny",
    ["wysokie jasnobrazowe grzyby"] = "borowik_szlachetny",
    ["twardy czerwony owoc"] = "borowka",
    ["twardych czerwonych owocow"] = "borowka",
    ["twarde czerwone owoce"] = "borowka",
    ["czarne aromatyczne ziarenko"] = "bulawinka",
    ["czarnych aromatycznych ziarenek"] = "bulawinka",
    ["czarne aromatyczne ziarenka"] = "bulawinka",
    ["rurkowaty oliwkowobrunatny kwiat"] = "bylica_cytwarowa",
    ["rurkowatych oliwkowobrunatnych kwiatow"] = "bylica_cytwarowa",
    ["rurkowate oliwkowobrunatne kwiaty"] = "bylica_cytwarowa",
    ["galeziasta szaroowlosiona lodyga"] = "bylica_piolun",
    ["galeziasta szaroowlosiona lodyge"] = "bylica_piolun",
    ["galeziastych szaroowlosionych lodyg"] = "bylica_piolun",
    ["galeziaste szaroowlosione lodygi"] = "bylica_piolun",
    ["kanciasta rozgaleziona lodyga"] = "bylica_pospolita",
    ["kanciasta rozgaleziona lodyge"] = "bylica_pospolita",
    ["kanciastych rozgalezionych lodyg"] = "bylica_pospolita",
    ["kanciaste rozgalezione lodygi"] = "bylica_pospolita",
    ["mazisty bulwiasty grzyb"] = "casur",
    ["mazistych bulwiastych grzybow"] = "casur",
    ["maziste bulwiaste grzyby"] = "casur",
    ["zlociste spore ziolo"] = "cebula",
    ["zlocistych sporych ziol"] = "cebula",
    ["zlociste spore ziola"] = "cebula",
    ["smukla jasnozielona lodyga"] = "centuria",
    ["smukla jasnozielona lodyge"] = "centuria",
    ["smuklych jasnozielonych lodyg"] = "centuria",
    ["smukle jasnozielone lodygi"] = "centuria",
    ["wysoki blekitny kwiat"] = "chaber",
    ["wysokich blekitnych kwiatow"] = "chaber",
    ["wysokie blekitne kwiaty"] = "chaber",
    ["ciemny splatany korzen"] = "ciemiernik",
    ["ciemnych splatanych korzeni"] = "ciemiernik",
    ["ciemne splatane korzenie"] = "ciemiernik",
    ["zielony miesisty kwiat"] = "ciemiezyca",
    ["zielonych miesistych kwiatow"] = "ciemiezyca",
    ["zielone miesiste kwiaty"] = "ciemiezyca",
    ["ulistniona aromatyczna galazka"] = "czeremcha",
    ["ulistniona aromatyczna galazke"] = "czeremcha",
    ["ulistnionych aromatycznych galazek"] = "czeremcha",
    ["ulistnione aromatyczne galazki"] = "czeremcha",
    ["biala pachnaca cebulka"] = "czosnek",
    ["biala pachnaca cebulke"] = "czosnek",
    ["bialych pachnacych cebulek"] = "czosnek",
    ["biale pachnace cebulki"] = "czosnek",
    ["zolty jasny kwiat"] = "deliona",
    ["zoltych jasnych kwiatow"] = "deliona",
    ["zolte jasne kwiaty"] = "deliona",
    ["lsniacy czerwony owoc"] = "deren",
    ["lsniacych czerwonych owocow"] = "deren",
    ["lsniace czerwone owoce"] = "deren",
    ["zielona postrzepiona galazka"] = "drabik",
    ["zielona postrzepiona galazke"] = "drabik",
    ["zielonych postrzepionych galazek"] = "drabik",
    ["zielone postrzepione galazki"] = "drabik",
    ["soczysty karminowy mech"] = "drath",
    ["soczystych karminowych mchow"] = "drath",
    ["soczyste karminowe mchy"] = "drath",
    ["czterokanciasta rozgaleziona lodyga"] = "dziurawiec",
    ["czterokanciasta rozgaleziona lodyge"] = "dziurawiec",
    ["czterokanciastych rozgalezionych lodyg"] = "dziurawiec",
    ["czterokanciaste rozgalezione lodygi"] = "dziurawiec",
    ["bialy maly kwiat"] = "glog",
    ["bialych malych kwiatow"] = "glog",
    ["biale male kwiaty"] = "glog",
    ["brazowawy fosforyzujacy mech"] = "grabiorog",
    ["brazowawych fosforyzujacych mchow"] = "grabiorog",
    ["brazowawe fosforyzujace mchy"] = "grabiorog",
    ["pachnacy snieznobialy kwiat"] = "grzybien",
    ["pachnacych snieznobialych kwiatow"] = "grzybien",
    ["pachnace snieznobiale kwiaty"] = "grzybien",
    ["grzybi suchy kapelusz"] = "hubka",
    ["grzybich suchych kapeluszy"] = "hubka",
    ["grzybie suche kapelusze"] = "hubka",
    ["zielona kwitnaca krzewinka"] = "hyzop",
    ["zielona kwitnaca krzewinke"] = "hyzop",
    ["zielonych kwitnacych krzewinek"] = "hyzop",
    ["zielone kwitnace krzewinki"] = "hyzop",
    ["maly fioletowy owoc"] = "jagoda",
    ["malych fioletowych owocow"] = "jagoda",
    ["male fioletowe owoce"] = "jagoda",
    ["wiotka kwitnaca galazka"] = "janowiec",
    ["wiotka kwitnaca galazke"] = "janowiec",
    ["wiotkich kwitnacych galazek"] = "janowiec",
    ["wiotkie kwitnace galazki"] = "janowiec",
    ["rozgaleziona wzniesiona lodyga"] = "jaskier",
    ["rozgaleziona wzniesiona lodyge"] = "jaskier",
    ["rozgalezionych wzniesionych lodyg"] = "jaskier",
    ["rozgalezione wzniesione lodygi"] = "jaskier",
    ["oliwkowozielona gietka galazka"] = "jemiola",
    ["oliwkowozielona gietka galazke"] = "jemiola",
    ["oliwkowozielonych gietkich galazek"] = "jemiola",
    ["oliwkowozielone gietkie galazki"] = "jemiola",
    ["maly czarny owoc"] = "jezyna",
    ["malych czarnych owocow"] = "jezyna",
    ["male czarne owoce"] = "jezyna",
    ["liliowy lejkowaty kwiat"] = "kakol",
    ["liliowych lejkowatych kwiatow"] = "kakol",
    ["liliowe lejkowate kwiaty"] = "kakol",
    ["brazowy duzy owoc"] = "kasztan",
    ["brazowych duzych owocow"] = "kasztan",
    ["brazowe duze owoce"] = "kasztan",
    ["kosmatoowlosiony kwiatostan"] = "kasztanowiec",
    ["kosmatoowlosionych kwiatostanow"] = "kasztanowiec",
    ["kosmatoowlosione kwiatostany"] = "kasztanowiec",
    ["wzniesiona owlosiona lodyga"] = "kocimietka",
    ["wzniesiona owlosiona lodyge"] = "kocimietka",
    ["wzniesionych owlosionych lodyg"] = "kocimietka",
    ["wzniesione owlosione lodygi"] = "kocimietka",
    ["brazowe okragle nasionko"] = "kola",
    ["brazowych okraglych nasionek"] = "kola",
    ["brazowe okragle nasionka"] = "kola",
    ["macznistoowlosiona szarawa roslina"] = "komosa",
    ["macznistoowlosiona szarawa rosline"] = "komosa",
    ["macznistoowlosionych szarawych roslin"] = "komosa",
    ["macznistoowlosione szarawe rosliny"] = "komosa",
    ["dluga lodyga"] = "konopie",
    ["dluga lodyge"] = "konopie",
    ["dlugich lodyg"] = "konopie",
    ["dlugie lodygi"] = "konopie",
    ["dluga ususzona lodyga"] = "ususzona_konopia",
    ["dluga ususzona lodyge"] = "ususzona_konopia",
    ["dlugich ususzonych lodyg"] = "ususzona_konopia",
    ["dlugie ususzone lodygi"] = "ususzona_konopia",
    ["wonny dzwonkowaty kwiatek"] = "konwalia",
    ["wonnych dzwonkowatych kwiatkow"] = "konwalia",
    ["wonne dzwonkowate kwiatki"] = "konwalia",
    ["wysoki czerwonawy grzyb"] = "kozlarz",
    ["wysokich czerwonawych grzybow"] = "kozlarz",
    ["wysokie czerwonawe grzyby"] = "kozlarz",
    ["pachnacy jasnozielony lisc"] = "krasnodrzew",
    ["pachnacych jasnozielonych lisci"] = "krasnodrzew",
    ["pachnace jasnozielone liscie"] = "krasnodrzew",
    ["zdrewniala zwinieta rurka"] = "kruszyna",
    ["zdrewniala zwinieta rurke"] = "kruszyna",
    ["zdrewnialych zwinietych rurek"] = "kruszyna",
    ["zdrewniale zwiniete rurki"] = "kruszyna",
    ["zoltawy powyginany korzen"] = "krzyzownica",
    ["zoltawych powyginanych korzeni"] = "krzyzownica",
    ["zoltawe powyginane korzenie"] = "krzyzownica",
    ["dziwne zoltoszare nasionko"] = "kulczyba",
    ["dziwnych zoltoszarych nasionek"] = "kulczyba",
    ["dziwne zoltoszare nasionka"] = "kulczyba",
    ["wiotka drobna lodyzka"] = "kurzyslad",
    ["wiotka drobna lodyzke"] = "kurzyslad",
    ["wiotkich drobnych lodyzek"] = "kurzyslad",
    ["wiotkie drobne lodyzki"] = "kurzyslad",
    ["sztywna smukla lodyga"] = "lak",
    ["sztywna smukla lodyge"] = "lak",
    ["sztywnych smuklych lodyg"] = "lak",
    ["sztywne smukle lodygi"] = "lak",
    ["fioletowy zwarty kwiatostan"] = "lawenda",
    ["fioletowych zwartych kwiatostanow"] = "lawenda",
    ["fioletowe zwarte kwiatostany"] = "lawenda",
    ["szary aromatyczny korzen"] = "lubczyk",
    ["szarych aromatycznych korzeni"] = "lubczyk",
    ["szare aromatyczne korzenie"] = "lubczyk",
    ["sztywny rozgaleziony korzen"] = "lukrecja",
    ["sztywnych rozgalezionych korzeni"] = "lukrecja",
    ["sztywne rozgalezione korzenie"] = "lukrecja",
    ["jasnozielona nieowlosiona lodyga"] = "lulecznica",
    ["jasnozielona nieowlosiona lodyge"] = "lulecznica",
    ["jasnozielonych nieowlosionych lodyg"] = "lulecznica",
    ["jasnozielone nieowlosione lodygi"] = "lulecznica",
    ["brudnozolty fioletowo-zylkowany kwiat"] = "lulek",
    ["brudnozoltych fioletowo-zylkowanych kwiatow"] = "lulek",
    ["brudnozolte fioletowo-zylkowane kwiaty"] = "lulek",
    ["aromatyczne ziele"] = "machorka",
    ["aromatycznych ziol"] = "machorka",
    ["aromatyczne ziola"] = "machorka",
    ["zdrewniala rozgaleziona krzewinka"] = "macznica",
    ["zdrewniala rozgaleziona krzewinke"] = "macznica",
    ["zdrewnialych rozgalezionych krzewinek"] = "macznica",
    ["zdrewniale rozgalezione krzewinki"] = "macznica",
    ["okazaly pachnacy kwiat"] = "mak_lekarski",
    ["okazalych pachnacych kwiatow"] = "mak_lekarski",
    ["okazale pachnace kwiaty"] = "mak_lekarski",
    ["piekny czerwony kwiat"] = "mak_polny",
    ["pieknych czerwonych kwiatow"] = "mak_polny",
    ["piekne czerwone kwiaty"] = "mak_polny",
    ["niewielki fioletowy kwiat"] = "makownik",
    ["niewielkich fioletowych kwiatow"] = "makownik",
    ["niewielkie fioletowe kwiaty"] = "makownik",
    ["maly czerwony owoc"] = "malina",
    ["malych czerwonych owocow"] = "malina",
    ["male czerwone owoce"] = "malina",
    ["bialy rozgaleziony korzen"] = "mandragora",
    ["bialych rozgalezionych korzeni"] = "mandragora",
    ["biale rozgalezione korzenie"] = "mandragora",
    ["rozwiniety korzen"] = "marzanna",
    ["rozwinietych korzeni"] = "marzanna",
    ["rozwiniete korzenie"] = "marzanna",
    ["nieduzy brazowy grzyb"] = "maslak",
    ["nieduzych brazowych grzybow"] = "maslak",
    ["nieduze brazowe grzyby"] = "maslak",
    ["owlosiony aromatyczny lisc"] = "melisa",
    ["owlosionych aromatycznych lisci"] = "melisa",
    ["owlosione aromatyczne liscie"] = "melisa",
    ["owlosiony aromatyczny ususzony lisc"] = "ususzona_melisa",
    ["owlosionych aromatycznych ususzonych lisci"] = "ususzona_melisa",
    ["owlosione aromatyczne ususzone liscie"] = "ususzona_melisa",
    ["okraglawy aromatyczny lisc"] = "mieta",
    ["okraglawych aromatycznych lisci"] = "mieta",
    ["okraglawe aromatyczne liscie"] = "mieta",
    ["zlocistozolty kwiat"] = "mniszek",
    ["zlocistozoltych kwiatow"] = "mniszek",
    ["zlocistozolte kwiaty"] = "mniszek",
    ["miedzianozielony fosforyzujacy grzyb"] = "muchomor_cesarski",
    ["miedzianozielonych fosforyzujacych grzybow"] = "muchomor_cesarski",
    ["miedzianozielone fosforyzujace grzyby"] = "muchomor_cesarski",
    ["delikatny czerwony grzyb"] = "muchomor_czerwony",
    ["delikatnych czerwonych grzybow"] = "muchomor_czerwony",
    ["delikatne czerwone grzyby"] = "muchomor_czerwony",
    ["delikatny jasny grzyb"] = "muchomor_sromotnikowy",
    ["delikatnych jasnych grzybow"] = "muchomor_sromotnikowy",
    ["delikatne jasne grzyby"] = "muchomor_sromotnikowy",
    ["jasnopomaranczowy kwiat"] = "nagietek",
    ["jasnopomaranczowych kwiatow"] = "nagietek",
    ["jasnopomaranczowe kwiaty"] = "nagietek",
    ["srebrzystoszary owlosiony lisc"] = "naparstnica",
    ["srebrzystoszarych owlosionych lisci"] = "naparstnica",
    ["srebrzystoszare owlosione liscie"] = "naparstnica",
    ["jasnobrazowa ulistniona lodyga"] = "nawloc",
    ["jasnobrazowa ulistniona lodyge"] = "nawloc",
    ["jasnobrazowych ulistnionych lodyg"] = "nawloc",
    ["jasnobrazowe ulistnione lodygi"] = "nawloc",
    ["smukla zielona lodyga"] = "nostrzyk",
    ["smukla zielona lodyge"] = "nostrzyk",
    ["smuklych zielonych lodyg"] = "nostrzyk",
    ["smukle zielone lodygi"] = "nostrzyk",
    ["eliptyczny zaostrzony lisc"] = "ogorecznik",
    ["eliptycznych zaostrzonych lisci"] = "ogorecznik",
    ["eliptyczne zaostrzone liscie"] = "ogorecznik",
    ["kolczasta wysuszona roslina"] = "oset",
    ["kolczasta wysuszona rosline"] = "oset",
    ["kolczastych wysuszonych roslin"] = "oset",
    ["kolczaste wysuszone rosliny"] = "oset",
    ["duzy fioletowy kwiat"] = "ostrozeczka",
    ["duzych fioletowych kwiatow"] = "ostrozeczka",
    ["duze fioletowe kwiaty"] = "ostrozeczka",
    ["galezista sinozielona lodyga"] = "ostrozen",
    ["galezista sinozielona lodyge"] = "ostrozen",
    ["galezistych sinozielonych lodyg"] = "ostrozen",
    ["galeziste sinozielone lodygi"] = "ostrozen",
    ["ciemne poskrecane klacze"] = "pieciornik",
    ["ciemnych poskrecanych klaczy"] = "pieciornik",
    ["ciemne poskrecane klacza"] = "pieciornik",
    ["ciemnoniebieski sluzowaty grzyb"] = "pierscieniak",
    ["ciemnoniebieskich sluzowatych grzybow"] = "pierscieniak",
    ["ciemnoniebieskie sluzowate grzyby"] = "pierscieniak",
    ["jasnozielony sluzowaty grzyb"] = "pierscieniak_gryn",
    ["jasnozielonych sluzowatych grzybow"] = "pierscieniak_gryn",
    ["jasnozielone sluzowate grzyby"] = "pierscieniak_gryn",
    ["szarozielony gabczasty porost"] = "plucnica",
    ["szarozielonych gabczastych porostow"] = "plucnica",
    ["szarozielone gabczaste porosty"] = "plucnica",
    ["zolty jaskrawy kwiat"] = "podbial",
    ["zoltych jaskrawych kwiatow"] = "podbial",
    ["zolte jaskrawe kwiaty"] = "podbial",
    ["sredni kasztanowobrazowy grzyb"] = "podgrzybek",
    ["srednich kasztanowobrazowych grzybow"] = "podgrzybek",
    ["srednie kasztanowobrazowe grzyby"] = "podgrzybek",
    ["grube walcowate klacze"] = "pokrzyk",
    ["grubych walcowatych klaczy"] = "pokrzyk",
    ["grube walcowate klacza"] = "pokrzyk",
    ["kanciasta parzaca lodyga"] = "pokrzywa",
    ["kanciasta parzaca lodyge"] = "pokrzywa",
    ["kanciastych parzacych lodyg"] = "pokrzywa",
    ["kanciaste parzace lodygi"] = "pokrzywa",
    ["pierzasty ogonkowy lisc"] = "potoslin",
    ["pierzastych ogonkowych lisci"] = "potoslin",
    ["pierzaste ogonkowe liscie"] = "potoslin",
    ["szorstka ciemnozielona galazka"] = "poziewnik",
    ["szorstka ciemnozielona galazke"] = "poziewnik",
    ["szorstkich ciemnozielonych galazek"] = "poziewnik",
    ["szorstkie ciemnozielone galazki"] = "poziewnik",
    ["niewielki czerwony owoc"] = "poziomka",
    ["niewielkich czerwonych owocow"] = "poziomka",
    ["niewielkie czerwone owoce"] = "poziomka",
    ["kremowy owlosiony kwiat"] = "przelot",
    ["kremowych owlosionych kwiatow"] = "przelot",
    ["kremowe owlosione kwiaty"] = "przelot",
    ["kremowy owlosiony ususzony kwiat"] = "ususzony_przelot",
    ["kremowych owlosionych ususzonych kwiatow"] = "ususzony_przelot",
    ["kremowe owlosione ususzone kwiaty"] = "ususzony_przelot",
    ["rozgowata zoltozielona galazka"] = "przesl",
    ["rozgowata zoltozielona galazke"] = "przesl",
    ["rozgowatych zoltozielonych galazek"] = "przesl",
    ["rozgowate zoltozielone galazki"] = "przesl",
    ["czerwonawy duzy lisc"] = "rabarbar",
    ["czerwonawych duzych lisci"] = "rabarbar",
    ["czerwonawe duze liscie"] = "rabarbar",
    ["zoltoszary niepozorny korzen"] = "ranog",
    ["zoltoszarych niepozornych korzeni"] = "ranog",
    ["zoltoszare niepozorne korzenie"] = "ranog",
    ["zoltoszary niepozorny ususzony korzen"] = "ususzony_ranog",
    ["zoltoszarych niepozornych ususzonych korzeni"] = "ususzony_ranog",
    ["zoltoszare niepozorne ususzone korzenie"] = "ususzony_ranog",
    ["szarawe pogiete klacze"] = "rauwolfia",
    ["szarawych pogietych klacze"] = "rauwolfia",
    ["szarawe pogiete klacza"] = "rauwolfia",
    ["zielony galezisty ped"] = "rdest_ptasi",
    ["zielonych galezistych pedow"] = "rdest_ptasi",
    ["zielone galeziste pedy"] = "rdest_ptasi",
    ["grube wygiete klacze"] = "rdest_wezownik",
    ["grubych wygietych klaczy"] = "rdest_wezownik",
    ["grube wygiete klacza"] = "rdest_wezownik",
    ["ciemnozielona rozwarta rozyczka"] = "rojnik",
    ["ciemnozielona rozwarta rozyczke"] = "rojnik",
    ["ciemnozielonych rozwartych rozyczek"] = "rojnik",
    ["ciemnozielone rozwarte rozyczki"] = "rojnik",
    ["bialokwitnaca drobna roslinka"] = "rosiczka",
    ["bialokwitnaca drobna roslinke"] = "rosiczka",
    ["bialokwitnacych drobnych roslinek"] = "rosiczka",
    ["bialokwitnace drobne roslinki"] = "rosiczka",
    ["drobny bialy kwiatek"] = "rumianek",
    ["drobnych bialych kwiatkow"] = "rumianek",
    ["drobne biale kwiatki"] = "rumianek",
    ["maly czerwony kwiat"] = "serce_kapitana",
    ["malych czerwonych kwiatow"] = "serce_kapitana",
    ["male czerwone kwiaty"] = "serce_kapitana",
    ["duza granatowa jagoda"] = "siezygron",
    ["duza granatowa jagode"] = "siezygron",
    ["duzych granatowych jagod"] = "siezygron",
    ["duze granatowe jagody"] = "siezygron",
    ["zielona trzeszczaca galazke"] = "skrzyp",
    ["zielonych trzeszczacych galazek"] = "skrzyp",
    ["zielone trzeszczace galazki"] = "skrzyp",
    ["czarny niewielki owoc"] = "sliwa",
    ["czarnych niewielkich owocow"] = "sliwa",
    ["czarne niewielkie owoce"] = "sliwa",
    ["wysoki zolty kwiat"] = "starzec",
    ["wysokich zoltych kwiatow"] = "starzec",
    ["wysokie zolte kwiaty"] = "starzec",
    ["bialy zmutowany grzybek"] = "stroczek",
    ["bialego zmutowanego grzybka"] = "stroczek",
    ["bialych zmutowanych grzybkow"] = "stroczek",
    ["biale zmutowane grzybki"] = "stroczek",
    ["rozgaleziona owlosiona lodyga"] = "stroiczka",
    ["rozgaleziona owlosiona lodyge"] = "stroiczka",
    ["rozgalezionych owlosionych lodyg"] = "stroiczka",
    ["rozgalezione owlosione lodygi"] = "stroiczka",
    ["jaskrawozolty drobny kwiat"] = "stulicha",
    ["jaskrawozoltych drobnych kwiatow"] = "stulicha",
    ["jaskrawozolte drobne kwiaty"] = "stulicha",
    ["drobna ukwiecona galazka"] = "swietlik",
    ["drobna ukwiecona galazke"] = "swietlik",
    ["drobnych ukwieconych galazek"] = "swietlik",
    ["drobne ukwiecone galazki"] = "swietlik",
    ["jasnofioletowy delikatny kwiat"] = "szafran",
    ["jasnofioletowych delikatnych kwiatow"] = "szafran",
    ["jasnofioletowe delikatne kwiaty"] = "szafran",
    ["jasnofioletowy delikatny ususzony kwiat"] = "ususzony_szafran",
    ["jasnofioletowych delikatnych ususzonych kwiatow"] = "ususzony_szafran",
    ["jasnofioletowe delikatne ususzone kwiaty"] = "ususzony_szafran",
    ["pomaranczowy maly korzen"] = "szalej",
    ["pomaranczowych malych korzeni"] = "szalej",
    ["pomaranczowe male korzenie"] = "szalej",
    ["strzalkowaty aromatyczny lisc"] = "szczaw",
    ["strzalkowatych aromatycznych lisci"] = "szczaw",
    ["strzalkowate aromatyczne liscie"] = "szczaw",
    ["rozdeta aromatyczna lodyga"] = "szczwol",
    ["rozdeta aromatyczna lodyge"] = "szczwol",
    ["rozdetych aromatycznych lodyg"] = "szczwol",
    ["rozdete aromatyczne lodygi"] = "szczwol",
    ["aromatyczne klacze"] = "tatarak",
    ["aromatycznych klaczy"] = "tatarak",
    ["aromatyczne klacza"] = "tatarak",
    ["wzniesiona ukwiecona lodyga"] = "tojad",
    ["wzniesiona ukwiecona lodyge"] = "tojad",
    ["wzniesionych ukwieconych lodyg"] = "tojad",
    ["wzniesione ukwiecone lodygi"] = "tojad",
    ["zielone lancetowate liscie"] = "trawa",
    ["zielonych lancetowatych lisci"] = "trawa",
    ["zielone lancetowate liscie"] = "trawa",
    ["duze pomarszczone liscie"] = "tyton",
    ["duzych pomarszczonych lisci"] = "tyton",
    ["duze pomarszczone liscie"] = "tyton",
    ["niepozorna sinozielona roslinka"] = "urzet",
    ["niepozorna sinozielona roslinke"] = "urzet",
    ["niepozornych sinozielonych roslinek"] = "urzet",
    ["niepozorne sinozielone roslinki"] = "urzet",
    ["rozowy pachnacy kwiat"] = "roza_ogrodowa",
    ["rozowy pachnacy kwiat"] = "roza_ogrodowa",
    ["rozowych pachnacych kwiatow"] = "roza_ogrodowa",
    ["rozowe pachnace kwiaty"] = "roza_ogrodowa",
    ["zdrewniala rozgaleziona ususzona krzewinka"] = "ususzona_macznica",
    ["zdrewniale rozgalezione ususzone krzewinki"] = "ususzona_macznica",
    ["zdrewniala rozgaleziona ususzona krzewinke"] = "ususzona_macznica",
    ["zolty rurkowaty kwiat"] = "wrotycz",
    ["zoltych rurkowatych kwiatow"] = "wrotycz",
    ["zolte rurkowate kwiaty"] = "wrotycz",
    ["zdlugi zielonobrunatny strak"] = "perelkowiec",
    ["zdlugich zielonobrunatnych strakow"] = "perelkowiec",
    ["zdlugie zielonobrunatne straki"] = "perelkowiec",
    ["zielona trzeszczaca galazka"] = "skrzyp",
    ["zielonych trzeszczacych galazek"] = "skrzyp",
    ["zielone trzeszczace galazki"] = "skrzyp",
}

herbs["herbs_details"] =
{
    ["aralia"] = { ["desc"] = "szary kolczasty korzen", ["acc"] = "szary kolczasty korzen", ["details"] = "przezuj: +odp <olive_drab>-zmc <grey> trj" },
    ["arnika"] = { ["desc"] = "zlocistopomaranczowy duzy kwiat", ["acc"] = "zlocistopomaranczowy duzy kwiat", ["details"] = "zjedz: <olive_drab>-zmc<grey>, przedawk. trj" },
    ["babka"] = { ["desc"] = "rozetkowaty lancetowaty lisc", ["acc"] = "rozetkowaty lancetowaty lisc", ["details"] = "przyloz: <LimeGreen>+kon<grey>" },
    ["bagno"] = { ["desc"] = "brudnobrazowa cuchnaca galazka", ["acc"] = "brudnobrazowa cuchnaca galazke", ["details"] = "--" },
    ["boldoa"] = { ["desc"] = "szarozielony szorstki lisc", ["acc"] = "szarozielony szorstki lisc", ["details"] = "--" },
    ["barwinka"] = { ["desc"] = "fioletowy lejkowaty kwiat", ["acc"] = "fioletowy lejkowaty kwiat", ["details"] = "przyloz: <LimeGreen>+kon<grey>" },
    ["bez"] = { ["desc"] = "jasnobrunatna popekana galazka", ["acc"] = "jasnobrunatna popekana galazke", ["details"] = "--" },
    ["bielun"] = { ["desc"] = "duzy bialy kwiat", ["acc"] = "duzy bialy kwiat", ["details"] = "powachaj: +wyt" },
    ["bobotrutka"] = { ["desc"] = "czarna blyszczaca fasolka", ["acc"] = "czarna blyszczaca fasolke", ["details"] = "rozgryz: trj" },
    ["borowik_krolewski"] = { ["desc"] = "gruby brazowy grzyb", ["acc"] = "gruby brazowy grzyb", ["details"] = "--" },
    ["borowik_szatanski"] = { ["desc"] = "gruby szarawy grzyb", ["acc"] = "gruby szarawy grzyb", ["details"] = "--" },
    ["borowik_szlachetny"] = { ["desc"] = "wysoki jasnobrazowy grzyb", ["acc"] = "wysoki jasnobrazowy grzyb", ["details"] = "--" },
    ["borowka"] = { ["desc"] = "twardy czerwony owoc", ["acc"] = "twardy czerwony owoc", ["details"] = "--" },
    ["bulawinka"] = { ["desc"] = "czarne aromatyczne ziarenko", ["acc"] = "czarne aromatyczne ziarenko", ["details"] = "--" },
    ["bylica_cytwarowa"] = { ["desc"] = "rurkowaty oliwkowobrunatny kwiat", ["acc"] = "rurkowaty oliwkowobrunatny kwiat", ["details"] = "--" },
    ["bylica_piolun"] = { ["desc"] = "galeziasta szaroowlosiona lodyga", ["acc"] = "galeziasta szaroowlosiona lodyge", ["details"] = "--" },
    ["bylica_pospolita"] = { ["desc"] = "kanciasta rozgaleziona lodyga", ["acc"] = "kanciasta rozgaleziona lodyge", ["details"] = "przyloz: <olive_drab>-zmc <grey>" },
    ["casur"] = { ["desc"] = "mazisty bulwiasty grzyb", ["acc"] = "mazisty bulwiasty grzyb", ["details"] = "zjedz: +sil" },
    ["cebula"] = { ["desc"] = "zlociste spore ziolo", ["acc"] = "zlociste spore ziolo", ["details"] = "--" },
    ["centuria"] = { ["desc"] = "smukla jasnozielona lodyga", ["acc"] = "smukla jasnozielona lodyge", ["details"] = "zjedz: --" },
    ["chaber"] = { ["desc"] = "wysoki blekitny kwiat", ["acc"] = "wysoki blekitny kwiat", ["details"] = "-trj?" },
    ["ciemiernik"] = { ["desc"] = "ciemny splatany korzen", ["acc"] = "ciemny splatany korzen", ["details"] = "zjedz: -sil -zrc -kon trj" },
    ["ciemiezyca"] = { ["desc"] = "zielony miesisty kwiat", ["acc"] = "zielony miesisty kwiat", ["details"] = "zjedz: -sil, -zrc" },
    ["czeremcha"] = { ["desc"] = "ulistniona aromatyczna galazka", ["acc"] = "ulistniona aromatyczna galazke", ["details"] = "przezuj: 3x odp" },
    ["czosnek"] = { ["desc"] = "biala pachnaca cebulka", ["acc"] = "biala pachnaca cebulke", ["details"] = "--" },
    ["deliona"] = { ["desc"] = "zolty jasny kwiat", ["acc"] = "zolty jasny kwiat", ["details"] = "zjedz: <olive_drab>-zmc <grey>" },
    ["deren"] = { ["desc"] = "lsniacy czerwony owoc", ["acc"] = "lsniacy czerwony owoc", ["details"] = "--" },
    ["drabik"] = { ["desc"] = "zielona postrzepiona galazka", ["acc"] = "zielona postrzepiona galazke", ["details"] = "--" },
    ["drath"] = { ["desc"] = "soczysty karminowy mech", ["acc"] = "soczysty karminowy mech", ["details"] = "przezuj: +wyt" },
    ["dziurawiec"] = { ["desc"] = "czterokanciasta rozgaleziona lodyga", ["acc"] = "czterokanciasta rozgaleziona lodyge", ["details"] = "rozgryz: <LimeGreen>+kon<grey>" },
    ["glog"] = { ["desc"] = "bialy maly kwiat", ["acc"] = "bialy maly kwiat", ["details"] = "przezuj: <LimeGreen>+kon<grey> +zmc, zjedz: <olive_drab>-zmc    <grey>" },
    ["grabiorog"] = { ["desc"] = "brazowawy fosforyzujacy mech", ["acc"] = "brazowawy fosforyzujacy mech", ["details"] = "zjedz: -man" },
    ["grzybien"] = { ["desc"] = "pachnacy snieznobialy kwiat", ["acc"] = "pachnacy snieznobialy kwiat", ["details"] = "--" },
    ["hubka"] = { ["desc"] = "grzybi suchy kapelusz", ["acc"] = "grzybi suchy kapelusz", ["details"] = "--" },
    ["hyzop"] = { ["desc"] = "zielona kwitnaca krzewinka", ["acc"] = "zielona kwitnaca krzewinke", ["details"] = "zjedz: +gld" },
    ["jagoda"] = { ["desc"] = "maly fioletowy owoc", ["acc"] = "maly fioletowy owoc", ["details"] = "--" },
    ["janowiec"] = { ["desc"] = "wiotka kwitnaca galazka", ["acc"] = "wiotka kwitnaca galazke", ["details"] = "zjedz: +prg" },
    ["jaskier"] = { ["desc"] = "rozgaleziona wzniesiona lodyga", ["acc"] = "rozgaleziona wzniesiona lodyge", ["details"] = "trj, przezuj: oslepienie" },
    ["jemiola"] = { ["desc"] = "oliwkowozielona gietka galazka", ["acc"] = "oliwkowozielona gietka galazke", ["details"] = "zjedz: -kon, -sil" },
    ["jezyna"] = { ["desc"] = "maly czarny owoc", ["acc"] = "maly czarny owoc", ["details"] = "--" },
    ["kakol"] = { ["desc"] = "liliowy lejkowaty kwiat", ["acc"] = "liliowy lejkowaty kwiat", ["details"] = "zjedz: +gld, trj" },
    ["kasztan"] = { ["desc"] = "brazowy duzy owoc", ["acc"] = "brazowy duzy owoc", ["details"] = "--" },
    ["kasztanowiec"] = { ["desc"] = "kosmatoowlosiony kwiatostan", ["acc"] = "kosmatoowlosiony kwiatostan", ["details"] = "zjedz: <olive_drab>-zmc <grey>" },
    ["kocimietka"] = { ["desc"] = "wzniesiona owlosiona lodyga", ["acc"] = "wzniesiona owlosiona lodyge", ["details"] = "--" },
    ["kola"] = { ["desc"] = "brazowe okragle nasionko", ["acc"] = "brazowe okragle nasionko", ["details"] = "rozgryz: +wyt <olive_drab>-zmc <grey>-gld, zjedz:-gld" },
    ["komosa"] = { ["desc"] = "macznistoowlosiona szarawa roslina", ["acc"] = "macznistoowlosiona szarawa rosline", ["details"] = "przezuj: +wyt <olive_drab>-zmc<grey>, zjedz: +sil" },
    ["konopie"] = { ["desc"] = "dluga lodyga", ["acc"] = "dluga lodyge", ["details"] = "spal: odp na magie" },
    ["ususzona_konopia"] = { ["desc"] = "dluga ususzona lodyga", ["acc"] = "dluga ususzona lodyge", ["details"] = "spal: odp na magie" },
    ["konwalia"] = { ["desc"] = "wonny dzwonkowaty kwiatek", ["acc"] = "wonny dzwonkowaty kwiatek", ["details"] = "powachaj: -prg -panika" },
    ["kozlarz"] = { ["desc"] = "wysoki czerwonawy grzyb", ["acc"] = "wysoki czerwonawy grzyb", ["details"] = "--" },
    ["krasnodrzew"] = { ["desc"] = "pachnacy jasnozielony lisc", ["acc"] = "pachnacy jasnozielony lisc", ["details"] = "powachaj: -prg -gld" },
    ["kruszyna"] = { ["desc"] = "zdrewniala zwinieta rurka", ["acc"] = "zdrewniala zwinieta rurke", ["details"] = "szkodliwe, zjedz: +gld" },
    ["krzyzownica"] = { ["desc"] = "zoltawy powyginany korzen", ["acc"] = "zoltawy powyginany korzen", ["details"] = "--" },
    ["kulczyba"] = { ["desc"] = "dziwne zoltoszare nasionko", ["acc"] = "dziwne zoltoszare nasionko", ["details"] = "zjedz: 2x -dis, trj" },
    ["kurzyslad"] = { ["desc"] = "wiotka drobna lodyzka", ["acc"] = "wiotka drobna lodyzke", ["details"] = "--" },
    ["lak"] = { ["desc"] = "sztywna smukla lodyga", ["acc"] = "sztywna smukla lodyge", ["details"] = "przezuj: <olive_drab>-zmc<grey>, rozgryz: +wyt" },
    ["lawenda"] = { ["desc"] = "fioletowy zwarty kwiatostan", ["acc"] = "fioletowy zwarty kwiatostan", ["details"] = "przyloz: <LimeGreen>+kon<grey> +zmc, zjedz: odp" },
    ["lubczyk"] = { ["desc"] = "szary aromatyczny korzen", ["acc"] = "szary aromatyczny korzen", ["details"] = "szkodliwe, zjedz: +gld" },
    ["lukrecja"] = { ["desc"] = "sztywny rozgaleziony korzen", ["acc"] = "sztywny rozgaleziony korzen", ["details"] = "przezuj: +prg rozgryz: --" },
    ["lulecznica"] = { ["desc"] = "jasnozielona nieowlosiona lodyga", ["acc"] = "jasnozielona nieowlosiona lodyge", ["details"] = "przezuj: <olive_drab>-zmc<grey>, przyloz: -panika" },
    ["lulek"] = { ["desc"] = "brudnozolty fioletowo-zylkowany kwiat", ["acc"] = "brudnozolty fioletowo-zylkowany kwiat", ["details"] = "trj" },
    ["machorka"] = { ["desc"] = "aromatyczne ziele", ["acc"] = "aromatyczne ziele", ["details"] = "--" },
    ["macznica"] = { ["desc"] = "zdrewniala rozgaleziona krzewinka", ["acc"] = "zdrewniala rozgaleziona krzewinke", ["details"] = "rozgryz: <LimeGreen>+kon<grey>" },
    ["mak_lekarski"] = { ["desc"] = "okazaly pachnacy kwiat", ["acc"] = "okazaly pachnacy kwiat", ["details"] = "szkodliwe, zjedz: -zrc, -spo" },
    ["mak_polny"] = { ["desc"] = "piekny czerwony kwiat", ["acc"] = "piekny czerwony kwiat", ["details"] = "zjedz: <LimeGreen>+kon<grey> +zme -zrc" },
    ["makownik"] = { ["desc"] = "niewielki fioletowy kwiat", ["acc"] = "niewielki fioletowy kwiat", ["details"] = "zjedz: <LimeGreen>+kon<grey>" },
    ["malina"] = { ["desc"] = "maly czerwony owoc", ["acc"] = "maly czerwony owoc", ["details"] = "--" },
    ["mandragora"] = { ["desc"] = "bialy rozgaleziony korzen", ["acc"] = "bialy rozgaleziony korzen", ["details"] = "przezuj: <medium_turquoise>+man<grey>" },
    ["marzanna"] = { ["desc"] = "rozwiniety korzen", ["acc"] = "rozwiniety korzen", ["details"] = "--" },
    ["maslak"] = { ["desc"] = "nieduzy brazowy grzyb", ["acc"] = "nieduzy brazowy grzyb", ["details"] = "--" },
    ["ususzona_melisa"] = { ["desc"] = "owlosiony aromatyczny ususzony lisc", ["acc"] = "owlosiony aromatyczny ususzony lisc", ["details"] = "przezuj: odp" },
    ["melisa"] = { ["desc"] = "owlosiony aromatyczny lisc", ["acc"] = "owlosiony aromatyczny lisc", ["details"] = "przezuj: odp" },
    ["mieta"] = { ["desc"] = "okraglawy aromatyczny lisc", ["acc"] = "okraglawy aromatyczny lisc", ["details"] = "rozetrzyj: <LimeGreen>+kon<grey> +zmc, powachaj: <olive_drab>-zmc<grey>" },
    ["mniszek"] = { ["desc"] = "zlocistozolty kwiat", ["acc"] = "zlocistozolty kwiat", ["details"] = "przezuj: <LimeGreen>+kon<grey> +zmc" },
    ["muchomor_cesarski"] = { ["desc"] = "miedzianozielony fosforyzujacy grzyb", ["acc"] = "miedzianozielony fosforyzujacy grzyb", ["details"] = "!trj" },
    ["muchomor_czerwony"] = { ["desc"] = "delikatny czerwony grzyb", ["acc"] = "delikatny czerwony grzyb", ["details"] = "!trj" },
    ["muchomor_sromotnikowy"] = { ["desc"] = "delikatny jasny grzyb", ["acc"] = "delikatny jasny grzyb", ["details"] = "!trj" },
    ["nagietek"] = { ["desc"] = "jasnopomaranczowy kwiat", ["acc"] = "jasnopomaranczowy kwiat", ["details"] = "przyloz: <LimeGreen>+kon<grey> +zmc" },
    ["naparstnica"] = { ["desc"] = "srebrzystoszary owlosiony lisc", ["acc"] = "srebrzystoszary owlosiony lisc", ["details"] = "zjedz: <olive_drab>-zmc<grey>" },
    ["nawloc"] = { ["desc"] = "jasnobrazowa ulistniona lodyga", ["acc"] = "jasnobrazowa ulistniona lodyge", ["details"] = "rozgryz: +gld +prg zjedz: --" },
    ["nostrzyk"] = { ["desc"] = "smukla zielona lodyga", ["acc"] = "smukla zielona lodyge", ["details"] = "przezuj: <olive_drab>-zmc<grey>, rozgryz: -kon +gld" },
    ["ogorecznik"] = { ["desc"] = "eliptyczny zaostrzony lisc", ["acc"] = "eliptyczny zaostrzony lisc", ["details"] = "przezuj: +odw" },
    ["oset"] = { ["desc"] = "kolczasta wysuszona roslina", ["acc"] = "kolczasta wysuszona rosline", ["details"] = "przezuj: -kon" },
    ["ostrozeczka"] = { ["desc"] = "duzy fioletowy kwiat", ["acc"] = "duzy fioletowy kwiat", ["details"] = "zjedz: +prg, trj" },
    ["ostrozen"] = { ["desc"] = "galezista sinozielona lodyga", ["acc"] = "galezista sinozielona lodyge", ["details"] = "-" },
    ["perelkowiec"] = { ["desc"] = "zdlugi zielonobrunatny strak", ["acc"] = "zdlugi zielonobrunatny strak", ["details"] = "--" },
    ["pieciornik"] = { ["desc"] = "ciemne poskrecane klacze", ["acc"] = "ciemne poskrecane klacze", ["details"] = "rozgryz: <LimeGreen>+kon<grey> +zmc" },
    ["pierscieniak"] = { ["desc"] = "ciemnoniebieski sluzowaty grzyb", ["acc"] = "ciemnoniebieski sluzowaty grzyb", ["details"] = "zjedz: --" },
    ["pierscieniak_gryn"] = { ["desc"] = "jasnozielony sluzowaty grzyb", ["acc"] = "jasnozielone sluzowate grzyby", ["details"] = "zjedz: --" },
    ["plucnica"] = { ["desc"] = "szarozielony gabczasty porost", ["acc"] = "szarozielony gabczasty porost", ["details"] = "sproszkuj: -trj" },
    ["podbial"] = { ["desc"] = "zolty jaskrawy kwiat", ["acc"] = "zolty jaskrawy kwiat", ["details"] = "--" },
    ["podgrzybek"] = { ["desc"] = "sredni kasztanowobrazowy grzyb", ["acc"] = "sredni kasztanowobrazowy grzyb", ["details"] = "--" },
    ["pokrzyk"] = { ["desc"] = "grube walcowate klacze", ["acc"] = "grube walcowate klacze", ["details"] = "zjedz: -spo" },
    ["pokrzywa"] = { ["desc"] = "kanciasta parzaca lodyga", ["acc"] = "kanciasta parzaca lodyge", ["details"] = "zjedz: +prg, +gld" },
    ["potoslin"] = { ["desc"] = "pierzasty ogonkowy lisc", ["acc"] = "pierzasty ogonkowy lisc", ["details"] = "zjedz: -sil -dis -kon trj" },
    ["poziewnik"] = { ["desc"] = "szorstka ciemnozielona galazka", ["acc"] = "szorstka ciemnozielona galazke", ["details"] = "--" },
    ["poziomka"] = { ["desc"] = "niewielki czerwony owoc", ["acc"] = "niewielki czerwony owoc", ["details"] = "--" },
    ["przelot"] = { ["desc"] = "kremowy owlosiony kwiat", ["acc"] = "kremowy owlosiony kwiat", ["details"] = "sproszkuj: --" },
    ["ususzony_przelot"] = { ["desc"] = "kremowy owlosiony ususzony kwiat", ["acc"] = "kremowy owlosiony ususzony kwiat", ["details"] = "sproszkuj: <olive_drab>-zmc<grey> -man" },
    ["przesl"] = { ["desc"] = "rozgowata zoltozielona galazka", ["acc"] = "rozgowata zoltozielona galazke", ["details"] = "przezuj: +wyt" },
    ["rabarbar"] = { ["desc"] = "czerwonawy duzy lisc", ["acc"] = "czerwonawy duzy lisc", ["details"] = "--" },
    ["ranog"] = { ["desc"] = "zoltoszary niepozorny korzen", ["acc"] = "zoltoszary niepozorny korzen", ["details"] = "przezuj: -trj <LimeGreen>+kon<grey>" },
    ["ususzony_ranog"] = { ["desc"] = "zoltoszary niepozorny korzen", ["acc"] = "zoltoszary niepozorny korzen", ["details"] = "przezuj: -trj <LimeGreen>+kon<grey>" },
    ["ususzona_macznica"] = { ["desc"] = "zdrewniala rozgaleziona ususzona krzewinka", ["acc"] = "zdrewniala rozgaleziona ususzona krzewinke", ["details"] = "--" },
    ["rauwolfia"] = { ["desc"] = "szarawe pogiete klacze", ["acc"] = "szarawe pogiete klacze", ["details"] = "--" },
    ["rdest_ptasi"] = { ["desc"] = "zielony galezisty ped", ["acc"] = "zielony galezisty ped", ["details"] = "przyloz: <LimeGreen>+kon<grey>" },
    ["rdest_wezownik"] = { ["desc"] = "grube wygiete klacze", ["acc"] = "grube wygiete klacze", ["details"] = "przezuj: --" },
    ["rojnik"] = { ["desc"] = "ciemnozielona rozwarta rozyczka", ["acc"] = "ciemnozielona rozwarta rozyczke", ["details"] = "zjedz: +pij" },
    ["rosiczka"] = { ["desc"] = "bialokwitnaca drobna roslinka", ["acc"] = "bialokwitnaca drobna roslinke", ["details"] = "polknij: <medium_turquoise>+int<grey>" },
    ["roza_ogrodowa"] = { ["desc"] = "rozowy pachnacy kwiat", ["acc"] = "rozowy pachnacy kwiat", ["details"] = "--" },
    ["rumianek"] = { ["desc"] = "drobny bialy kwiatek", ["acc"] = "drobny bialy kwiatek", ["details"] = "--" },
    ["serce_kapitana"] = { ["desc"] = "maly czerwony kwiat", ["acc"] = "maly czerwony kwiat", ["details"] = "przezuj: <LimeGreen>+kon<grey> -zrc -int" },
    ["siezygron"] = { ["desc"] = "duza granatowa jagoda", ["acc"] = "duza granatowa jagode", ["details"] = "rozgryz: -trj" },
    ["skrzyp"] = { ["desc"] = "zielona trzeszczaca galazka", ["acc"] = "zielona trzeszczaca galazke", ["details"] = "--" },
    ["sliwa"] = { ["desc"] = "czarny niewielki owoc", ["acc"] = "czarny niewielki owoc", ["details"] = "--" },
    ["starzec"] = { ["desc"] = "wysoki zolty kwiat", ["acc"] = "wysoki zolty kwiat", ["details"] = "zjedz: trj" },
    ["stroczek"] = { ["desc"] = "bialy zmutowany grzybek", ["acc"] = "bialego zmutowanego grzybka", ["details"] = "zjedz: trj" },
    ["stroiczka"] = { ["desc"] = "rozgaleziona owlosiona lodyga", ["acc"] = "rozgaleziona owlosiona lodyge", ["details"] = "trj" },
    ["stulicha"] = { ["desc"] = "jaskrawozolty drobny kwiat", ["acc"] = "jaskrawozolty drobny kwiat", ["details"] = "trj" },
    ["swietlik"] = { ["desc"] = "drobna ukwiecona galazka", ["acc"] = "drobna ukwiecona galazke", ["details"] = "rozgryz: <medium_turquoise>+spo<grey>" },
    ["szafran"] = { ["desc"] = "jasnofioletowy delikatny kwiat", ["acc"] = "jasnofioletowy delikatny kwiat", ["details"] = "zjedz: +wyt" },
    ["ususzony_szafran"] = { ["desc"] = "jasnofioletowy delikatny ususzony kwiat", ["acc"] = "jasnofioletowy delikatny ususzony kwiat", ["details"] = "zjedz: <LimeGreen>+kon<grey>" },
    ["szalej"] = { ["desc"] = "pomaranczowy maly korzen", ["acc"] = "pomaranczowy maly korzen", ["details"] = "trj" },
    ["szalwia"] = { ["desc"] = "zaostrzony podluzny lisc", ["acc"] = "zaostrzony podluzny lisc", ["details"] = "?" },
    ["szczaw"] = { ["desc"] = "strzalkowaty aromatyczny lisc", ["acc"] = "strzalkowaty aromatyczny lisc", ["details"] = "przezuj: <LimeGreen>+kon<grey>" },
    ["szczwol"] = { ["desc"] = "rozdeta aromatyczna lodyga", ["acc"] = "rozdeta aromatyczna lodyge", ["details"] = "zjedz: -kon, trj -zrc" },
    ["tatarak"] = { ["desc"] = "aromatyczne klacze", ["acc"] = "aromatyczne klacze", ["details"] = "--" },
    ["tojad"] = { ["desc"] = "wzniesiona ukwiecona lodyga", ["acc"] = "wzniesiona ukwiecona lodyge", ["details"] = "trj" },
    ["trawa"] = { ["desc"] = "zielone lancetowate liscie", ["acc"] = "zielone lancetowate liscie", ["details"] = "--" },
    ["tyton"] = { ["desc"] = "duze pomarszczone liscie", ["acc"] = "duze pomarszczone liscie", ["details"] = "--" },
    ["urzet"] = { ["desc"] = "niepozorna sinozielona roslinka", ["acc"] = "niepozorne sinozielona roslinki", ["details"] = "--" },
    ["wrotycz"] = { ["desc"] = "zolty rurkowaty kwiat", ["acc"] = "zolty rurkowaty kwiat", ["details"] = "powachaj: +odp na trucizne" },
}

