function amap:print_db()
    cecho("+-------------------------- <green>Arkadia mapper, ver " .. string.sub(amap.ver .. "   ", 0, 5) .. "<grey> ---------------------------+\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Dostepne KOMENDY:<grey>                                                              |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/pokazuj_notki<grey> - czy pokazywac automatycznie notki.                            |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/lok_nazwa [nazwa]<grey> - ustawi <light_slate_blue>[nazwe]<grey> aktualnej lokacji.                         |\n")
    cecho("| <light_slate_blue>/lok_nazwa [id] [nazwa]<grey> - to co powyzej, ale dla tego <light_slate_blue>[id]<grey> lokacji.            |\n")
    cecho("| <light_slate_blue>/lok_opis [opis]<grey> - ustawi <light_slate_blue>[opis]<grey> aktualnej lokacji.                            |\n")
    cecho("| <light_slate_blue>/lok_opis [id] [opis]<grey> - to co powyzej, ale dla tego <light_slate_blue>[id]<grey> lokacji.              |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/przeszukaj_mape [nazwa]<grey> - przeszuka mape (nazwy i opisy) po tej <light_slate_blue>[nazwie]<grey>.     |\n")
    cecho("| Pokaze tylko 5 wynikow (najblizszych w odniesieniu do aktualnej lokacji).      |\n")
    cecho("| <light_slate_blue>/przeszukaj_mape! [nazwa]<grey> - przeszuka mape (nazwy i opisy) po tej <light_slate_blue>[nazwie]<grey>.    |\n")
    cecho("| Pokaze wszystkie wyniki, rowniez w kolejnosci odleglosci od aktualnej lokacji. |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/lok_notka [nazwa]<grey> - ustawi <light_slate_blue>[notke]<grey> aktualnej lokacji.                         |\n")
    cecho("| <light_slate_blue>/lok_notka [id] [nazwa]<grey> - to co powyzej, ale dla tego <light_slate_blue>[id]<grey> lokacji.            |\n")
    cecho("| <light_slate_blue>/lok_notka-<grey> - zresetuje notke aktualnej lokacji                                |\n")
    cecho("| <light_slate_blue>/lok_notka- [id]<grey> - to co powyzej, ale dla tego <light_slate_blue>[id]<grey> lokacji.                   |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/lok_bind [bind_string]<grey> - ustawi binda do aktualnej lokacji.                   |\n")
    cecho("| <red>!! UWAGA !!<grey>                                                                    |\n")
    cecho("| Komendy sa rozdzielone #, opoznienia sa rozdzielone *                          |\n")

    cecho("| Przykladowo: '/lok_bind fuknij#westchnij#usmiech' wykona wszystkie             |\n")
    cecho("| trzy komendy naraz.                                                            |\n")
    cecho("| '/lok_bind fuknij#westchnij*0.7#usmiech*2' wykona najpierw fuknij, nastepnie   |\n")
    cecho("| po 0.7 sekundy wykona 'westchnij', nastepnie po 2 sekundach (od czasu          |\n")
    cecho("| wcisniecia komendy) wykona 'usmiech'.                                          |\n")
    cecho("| Opoznienia sa liczone wzgledem nacisniecia komendy! Dlatego jesli uzywamy      |\n")
    cecho("| jakiejkolwiek wartosci w jednej z komend to wtedy kazda nastepna powinna miec  |\n")
    cecho("| taki sam lub wiekszy delay aby wykonala sie w odpowiedniej sekwencji.          |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/lok_bind_id [id] [bind_string]<grey> - to samo co wyzej tylko dla <light_slate_blue>[id]<grey> lokacji.     |\n")
    cecho("| <light_slate_blue>/lok_bind-<grey> - usuwa binda z aktualnej lokacji.                                  |\n")
    cecho("| <light_slate_blue>/lok_bind- [id]<grey> - usuwa binda z lokacji o <light_slate_blue>[id]<grey>.                                |\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Klawisz do bindow: CTRL + p<grey>                                                    |\n")
    cecho("| <light_slate_blue>/pokazuj_bindy<grey> - wlacza/wylacza pokazywanie bindow                             |\n")
    cecho("| po wejsciu na lokacje. Domyslnie wlaczone, mozna zmienic domyslne ustawienie   |\n")
    cecho("| w ustawieniach (patrz README)                                                  |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/pre_walk! [komendy_oddzielone_#]<grey> - od tej lokacji zacznie wykonywac te        |\n")
    cecho("| komendy przed kolejnym ruchem                                                  |\n")
    cecho("| <light_slate_blue>/post_walk! [komendy_oddzielone_#]<grey> - od tej lokacji zacznie wykonywac te       |\n")
    cecho("| komendy po kolejnym ruchu                                                      |\n")
    cecho("| <light_slate_blue>/pwalk!- [komendy_oddzielone_#]<grey> - Na tej lokacji komendy pre i post zostana    |\n")
    cecho("| skasowane.                                                                     |\n")
    cecho("| <light_slate_blue>/pwalk!!- [komendy_oddzielone_#]<grey> - Usunie wszystkie przypisania pre/post/reset |\n")
    cecho("| w tej lokacji.                                                                 |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/lok_team_fo [przejscie_string]#[kierunek]<grey> - doda skojarzenie <light_slate_blue>[przejscie]<grey> w    |\n")
    cecho("| tym <light_slate_blue>[kierunku]<grey>.                                                                |\n")
    cecho("| Przykladowo, jesli mamy lokacje z wyjscie do 'gospody' i string podazania jest:|\n")
    cecho("| 'Podazasz za ... do gospody' to mozna dodac na aktualnej lokacji:              |\n")
    cecho("| '/lok_team_fo gospody#gospoda'                                                 |\n")
    cecho("| Czasami jest tak, ze wyjscie jest standardowe (w kierunku 'w'), a jest tekst:  |\n")
    cecho("| 'Podazasz za ... przez rzeke', wtedy trzeba dac:                               |\n")
    cecho("| '/lok_team_fo rzeke#w'                                                         |\n")
    cecho("| <light_slate_blue>/lok_team_fo_id [id] [przejscie_string]#[kierunek]<grey> - to samo dla <light_slate_blue>[id]<grey> lokacji. |\n")
    cecho("| <light_slate_blue>/lok_team_fo-<grey> - usunie skojarzenia z aktualnej lokacji.                        |\n")
    cecho("| <light_slate_blue>/lok_team_fo- [id]<grey> - Usuwa skojarzenia z lokacji o <light_slate_blue>[id]<grey>.                       |\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Wszystkie te informacje (nazwy, opisy, notki, bindy i specjalne przejscia)<grey>     |\n")
    cecho("| <yellow>sa wylistowane w komendzie '/lok' albo '/lok [id]'<grey>                             |\n")
    cecho("|                                                                                |\n")
    cecho("+--------------------------------------------------------------------------------+\n")
end

