misc.lvl_calc["stat_to_number"] = {
    ["slabiutki"] = 1,
    ["slabiutka"] = 1,
    ["watly"] = 2,
    ["watla"] = 2,
    ["slaby"] = 3,
    ["slaba"] = 3,
    ["krzepki"] = 4,
    ["krzepka"] = 4,
    ["silny"] = 5,
    ["silna"] = 5,
    ["mocny"] = 6,
    ["mocna"] = 6,
    ["potezny"] = 7,
    ["potezna"] = 7,
    ["mocarny"] = 8,
    ["mocarna"] = 8,
    ["epicko silny"] = 9,
    ["epicko silna"] = 9,
    ["nieskoordynowany"] = 1,
    ["nieskoordynowana"] = 1,
    ["niezreczny"] = 2,
    ["niezreczna"] = 2,
    ["niezgrabny"] = 3,
    ["niezgrabna"] = 3,
    ["sprawny"] = 4,
    ["sprawna"] = 4,
    ["zwinny"] = 5,
    ["zwinna"] = 5,
    ["zreczny"] = 6,
    ["zreczna"] = 6,
    ["gibki"] = 7,
    ["gibka"] = 7,
    ["akrobatyczny"] = 8,
    ["akrobatyczna"] = 8,
    ["epicko zreczny"] = 9,
    ["epicko zreczna"] = 9,
    ["charlawy"] = 1,
    ["cherlawa"] = 1,
    ["rachityczny"] = 2,
    ["rachityczna"] = 2,
    ["mizerny"] = 3,
    ["mizerna"] = 3,
    ["dobrze zbudowany"] = 4,
    ["dobrze zbudowana"] = 4,
    ["wytrzymaly"] = 5,
    ["wytrzymala"] = 5,
    ["twardy"] = 6,
    ["twarda"] = 6,
    ["muskularny"] = 7,
    ["muskularna"] = 7,
    ["atletyczny"] = 8,
    ["atletyczna"] = 8,
    ["epicko wytrzymaly"] = 9,
    ["epicko wytrzymala"] = 9,
    ["bezmyslny"] = 1,
    ["bezmyslna"] = 1,
    ["tepy"] = 2,
    ["tepa"] = 2,
    ["ograniczony"] = 3,
    ["ograniczona"] = 3,
    ["pojetny"] = 4,
    ["pojetna"] = 4,
    ["inteligentny"] = 5,
    ["inteligentna"] = 5,
    ["bystry"] = 6,
    ["bystra"] = 6,
    ["blyskotliwy"] = 7,
    ["blyskotliwa"] = 7,
    ["genialny"] = 8,
    ["genialna"] = 8,
    ["epicko inteligenty"] = 9,
    ["epicko inteligenta"] = 9,
    ["thorzliwy"] = 1,
    ["thorzliwa"] = 1,
    ["strachliwy"] = 2,
    ["strachliwa"] = 2,
    ["niepewny"] = 3,
    ["niepewna"] = 3,
    ["zdecydowany"] = 4,
    ["zdecydowana"] = 4,
    ["odwazny"] = 5,
    ["odwazna"] = 5,
    ["dzielny"] = 6,
    ["dzielna"] = 6,
    ["nieugiety"] = 7,
    ["nieugieta"] = 7,
    ["nieustraszony"] = 8,
    ["nieustraszona"] = 8,
    ["epicko odwazny"] = 9,
    ["epicko odwazna"] = 9,
    ["nadludzki poziom"] = 10,
}

misc.lvl_calc["val_to_next_to_number"] = {
    ["bardzo duzo"] = 0,
    ["duzo"] = 1,
    ["troche"] = 2,
    ["niewiele"] = 3,
    ["bardzo niewiele"] = 4,
}

misc.lvl_calc["stat_to_index"] = {
    ["sile"] = 1,
    ["zrecznosc"] = 2,
    ["wytrzymalosc"] = 3,
    ["intelekt"] = 4,
    ["odwage"] = 5,
}

misc.lvl_calc["stat_to_real_lvl"] = {
    58,
    70,
    82,
    94,
    106,
    118,
    130,
    142,
    154,
    166,
    178,
    190,
}

misc.lvl_calc["real_lvl_string"] = {
    [1] = "ktos niedoswiadczony",
    [2] = "ktos kto widzial juz to i owo",
    [3] = "ktos kto pewnie stapa po swiecie",
    [4] = "ktos kto niejedno widzial",
    [5] = "ktos kto swoje przezyl",
    [6] = "ktos doswiadczony",
    [7] = "ktos kto wiele przeszedl",
    [8] = "ktos kto widzial kawal swiata",
    [9] = "ktos bardzo doswiadczony",
    [10] = "ktos kto zwiedzil caly swiat",
    [11] = "ktos wielce doswiadczony",
    [12] = "ktos kto widzial i doswiadczyl wszystkiego",
    [13] = "osoba owiana legenda",
}

