function scripts.people:print_help()
    cecho("+----------------------- <green>Arkadia skrypty, ver " .. string.sub(scripts.ver .. " ", 0, 5) .. "<grey> -----------------------+\n")
    cecho("|                                                                          |\n")
    cecho("| Prosty skrypt do trzymania informacji przedstawionych osob.              |\n")
    cecho("| Trzyma zarowno informacje o NPCach, jak i o graczach.                    |\n")
    cecho("| Wspiera rozne osoby z takim samym shortem.                               |\n")
    cecho("|                                                                          |\n")
    cecho("| <yellow>AKTUALNIE<grey> <tomato>wpisow w bazie: " .. string.sub(tostring(#db:fetch(scripts.people.db.people)) .. "       ", 0, 7) .. "<grey>                                        |\n")
    cecho("|                                                                          |\n")
    cecho("| Zapisywane sa nastepujace rzeczy:                                        |\n")
    cecho("|  » <yellow_green>id<grey> (wszystkie zapamietane postacie sa numerowane od 1 wzwyz),         |\n")
    cecho("|  » <yellow_green>imie<grey> (np. 'Ulav'),                                                    |\n")
    cecho("|  » <yellow_green>short<grey> (np. 'dojrzaly jednooki mezczyzna'),                            |\n")
    cecho("|  » <yellow_green>tytul<grey> ('Kelebor Wprawny Mysliwy, Starszy Rady Osadnikow, mezczyzna')  |\n")
    cecho("|  » <yellow_green>czas<grey> (dokladnie kiedy stworzono/zaktualizowano wpis tej postaci).     |\n")
    cecho("|                                                                          |\n")
    cecho("| W dodatku sa trzy dodatkowe pola:                                        |\n")
    cecho("|  » <yellow_green>gildia<grey> (wyswietlana przy imieniu postaci jesli jakakolwiek).          |\n")
    cecho("|  » <yellow_green>notka<grey> (np. 'jakas notka o tej postaci').                              |\n")
    cecho("|  » <yellow_green>wrog<grey> (jesli dana postac jest wrogiem).                                |\n")
    cecho("|                                                                          |\n")
    cecho("|                                                                          |\n")
    cecho("| <yellow>Dostepne KOMENDY:<grey>                                                        |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/ktoto [short]<grey> - Probuje wyszukac po <light_slate_blue>[shorcie]<grey>.                          |\n")
    cecho("| Dziala z calymi opisami albo czesciowymi.                                |\n")
    cecho("| Na przyklad: '/ktoto postawny dojrzaly mezczyzna' lub '/ktoto mezczyzna'.|\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/osoba [id]<grey> - Pokaze szczegoly osoby o <light_slate_blue>[id]<grey>.                             |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/przypomnij [imie]<grey> - Jesli w bazie jest ktos o tym <light_slate_blue>[imieniu]<grey> to pokaze.  |\n")
    cecho("| Na przyklad: '/przypomnij Ulav'.                                         |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/przeszukaj [fraza]<grey> - Przeszuka po calych tytulach.                      |\n")
    cecho("| Na przyklad: '/przeszukaj alderazzi', '/przeszukaj kupiec novigradzki'.  |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/widziani<grey> - Pokaze liste ostatnio widzianych ludzi.                      |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/dodaj_osobe [imie]#[short]#[title]<grey> - doda osobe do bazy.                |\n")
    cecho("| Wymagane sa co najmniej dwa pierwsze argumenty (<light_slate_blue>[imie]<grey> i <light_slate_blue>[short]<grey>).       |\n")
    cecho("| Moga byc trzy. <red>MUSZA<grey> byc rozdzielone znakiem '#'.                        |\n")
    cecho("| Np: '/dodaj_osobe Berghol#pijany zagubiony mezczyzna' lub                |\n")
    cecho("| Np: '/dodaj_osobe Berghol#pijany zagubiony mezczyzna#pijak z Wyzimy'.    |\n")
    cecho("| Np: '/dodaj_osobe #pijany zagubiony mezczyzna#nie znam imienia'.         |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/usun_osobe [id]<grey> - usunie osobe o <light_slate_blue>[id]<grey> z bazy.                           |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/aktualizuj [pole] [co] [wartosc]<grey> - zaktualizuj <light_slate_blue>pole<grey> osoby o <light_slate_blue>[id]<grey>        |\n")
    cecho("| do <light_slate_blue>wartosci<grey>. Dozwolone <light_slate_blue>pola<grey> to: 'imie', 'short' oraz 'title'.            |\n")
    cecho("| Np: '/aktualizuj 100 imie NoweImie' lub                                  |\n")
    cecho("| Np: '/aktualizuj 154 opis Nowy opis tej osoby'                           |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/dodaj_do_gildii [id] [gildia]<grey> - Przypisze postac <light_slate_blue>id<grey> do <light_slate_blue>[gildii]<grey>.        |\n")
    cecho("| Na przyklad: '/dodaj_do_gildii 1234 KG.                                  |\n")
    cecho("| <light_slate_blue>/dodaj_do_gildii [imie] [gildia]<grey> - Przypisze postac <light_slate_blue>Imie<grey> do <light_slate_blue>[gildii]<grey>.    |\n")
    cecho("| Na przyklad: '/dodaj_do_gildii ulav KG.                                  |\n")
    cecho("| Symbole Gildii: '/gildie'.                                               |\n")
    cecho("| Aby usunac, wystarczy wykonac pusta komende:                             |\n")
    cecho("| '/dodaj_do_gildii ulav' lub '/dodaj_do_gildii 1234'                      |\n")
    cecho("| Aby zmienic, wystarczy wykonac komende z nowa gildia.                    |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/zgildiowani [gildia]<grey> - wydrukuje liste postaci w <light_slate_blue>gildii<grey>.                |\n")
    cecho("|                                                                          |\n")
    cecho("| <light_slate_blue>/idzdo [id]<grey> - pojdzie do lokacji powiazanej z postacia o tym <light_slate_blue>[id]<grey>.       |\n")
    cecho("| Przydatne na poczcie przy paczkach, kiedy sa podobne imiona, takie       |\n")
    cecho("| imiona sa podkreslone na <orange>pomaranczowo<grey>.                                   |\n")
    cecho("| <light_slate_blue>/idzdo [id] [opoz]<grey> - powyzsze z opoznieniem<grey>.                             |\n")
    cecho("|                                                                          |\n")
    cecho("+--------------------------------------------------------------------------+\n")
end

