scripts["utils"] = scripts["utils"] or {}
scripts.counted_string_to_int = {
    ["jednej"] = 1,
    ["dwoch"] = 2,
    ["trzech"] = 3,
    ["czterech"] = 4,
    ["pieciu"] = 5,
    ["szesciu"] = 6,
    ["siedmiu"] = 7,
    ["osmiu"] = 8,
    ["dziewieciu"] = 9,
    ["dziesieciu"] = 10,
    ["jedenastu"] = 11,
    ["dwunastu"] = 12,
    ["trzynastu"] = 13,
    ["czternastu"] = 14,
    ["pietnastu"] = 15,
    ["szesnastu"] = 16,
    ["siedemnastu"] = 17,
    ["osiemnastu"] = 18,
    ["dziewietnastu"] = 19,
    ["dwudziestu"] = 20,
    ["dwudziestu jeden"] = 21,
    ["dwudziestu dwoch"] = 22,
    ["dwudziestu trzech"] = 23,
    ["dwudziestu czterech"] = 24,
    ["dwudziestu pieciu"] = 25,
    ["dwudziestu szesciu"] = 26,
    ["dwudziestu siedmiu"] = 27,
    ["dwudziestu osmiu"] = 28,
    ["dwudziestu dziewieciu"] = 29,
    ["trzydziestu"] = 30,
    ["trzydziestu jeden"] = 31,
    ["trzydziestu dwoch"] = 32,
    ["trzydziestu trzech"] = 33,
    ["trzydziestu czterech"] = 34,
    ["trzydziestu pieciu"] = 35,
    ["trzydziestu szesciu"] = 36,
    ["trzydziestu siedmiu"] = 37,
    ["trzydziestu osmiu"] = 38,
    ["trzydziestu dziewieciu"] = 39,
    ["czterdziestu"] = 40,
    ["czterdziestu jeden"] = 41,
    ["czterdziestu dwoch"] = 42,
    ["czterdziestu trzech"] = 43,
    ["czterdziestu czterech"] = 44,
    ["czterdziestu pieciu"] = 45,
    ["czterdziestu szesciu"] = 46,
    ["czterdziestu siedmiu"] = 47,
    ["czterdziestu osmiu"] = 48,
    ["czterdziestu dziewieciu"] = 49,
    ["piecdziesieciu"] = 50,
    ["piecdziesieciu jeden"] = 51,
    ["piecdziesieciu dwoch"] = 52,
    ["piecdziesieciu trzech"] = 53,
    ["piecdziesieciu czterech"] = 54,
    ["piecdziesieciu pieciu"] = 55,
    ["piecdziesieciu szesciu"] = 56,
    ["piecdziesieciu siedmiu"] = 57,
    ["piecdziesieciu osmiu"] = 58,
    ["piecdziesieciu dziewieciu"] = 59,
    ["szescdziesieciu"] = 60,
    ["szescdziesieciu jeden"] = 61,
    ["szescdziesieciu dwoch"] = 62,
    ["szescdziesieciu trzech"] = 63,
    ["szescdziesieciu czterech"] = 64,
    ["szescdziesieciu pieciu"] = 65,
    ["szescdziesieciu szesciu"] = 66,
    ["szescdziesieciu siedmiu"] = 67,
    ["szescdziesieciu osmiu"] = 68,
    ["szescdziesieciu dziewieciu"] = 69,
    ["siedemdziesieciu"] = 70
}

scripts.id_to_string = {
    [1] = "pierwszy",
    [2] = "drugi",
    [3] = "trzeci",
    [4] = "czwarty",
    [5] = "piaty",
    [6] = "szosty",
    [7] = "siodmy",
    [8] = "osmy",
    [9] = "dziewiaty",
    [10] = "dziesiaty",
    [11] = "jedenasty",
    [12] = "dwunasty",
    [13] = "trzynasty",
    [14] = "czternasty",
    [15] = "pietnasty",
    [16] = "szesnasty",
    [17] = "siedemnasty",
    [18] = "osiemnasty",
    [19] = "dziewietnasty",
    [20] = "dwudziesty",
    [21] = "dwudziesty pierwszy",
    [22] = "dwudziesty drugi",
    [23] = "dwudziesty trzeci",
    [24] = "dwudziesty czwarty",
    [25] = "dwudziesty piaty",
    [26] = "dwudziesty szosty",
    [27] = "dwudziesty siodmy",
    [28] = "dwudziesty osmy",
    [29] = "dwudziesty dziewiaty",
    [30] = "trzydziesty",
    [31] = "trzydziesty pierwszy",
    [32] = "trzydziesty drugi",
    [33] = "trzydziesty trzeci",
    [34] = "trzydziesty czwarty",
    [35] = "trzydziesty piaty",
    [36] = "trzydziesty szosty",
    [37] = "trzydziesty siodmy",
    [38] = "trzydziesty osmy",
    [39] = "trzydziesty dziewiaty",
    [40] = "czterdziesty",
}

scripts.id_to_string_biernik = {
    [1] = "pierwszego",
    [2] = "drugiego",
    [3] = "trzeciego",
    [4] = "czwartego",
    [5] = "piatego",
    [6] = "szostego",
    [7] = "siodmego",
    [8] = "osmego",
    [9] = "dziewiatego",
    [10] = "dziesiatego",
    [11] = "jedenastego",
    [12] = "dwunastego",
    [13] = "trzynastego",
    [14] = "czternastego",
    [15] = "pietnastego",
    [16] = "szesnastego",
    [17] = "siedemnastego",
    [18] = "osiemnastego",
    [19] = "dziewietnastego",
    [20] = "dwudziestego",
    [21] = "dwudziestego pierwszego",
    [22] = "dwudziestego drugiego",
    [23] = "dwudziestego trzeciego",
    [24] = "dwudziestego czwartego",
    [25] = "dwudziestego piatego",
    [26] = "dwudziestego szostego",
    [27] = "dwudziestego siodmego",
    [28] = "dwudziestego osmego",
    [29] = "dwudziestego dziewiatego",
    [30] = "trzydziestego",
    [31] = "trzydziestego pierwszego",
    [32] = "trzydziestego drugiego",
    [33] = "trzydziestego trzeciego",
    [34] = "trzydziestego czwartego",
    [35] = "trzydziestego piatego",
    [36] = "trzydziestego szostego",
    [37] = "trzydziestego siodmego",
    [38] = "trzydziestego osmego",
    [39] = "trzydziestego dziewiatego",
    [40] = "czterdziestego",
}

scripts.string_to_liczebnik = {
    ["dwa"] = 2,
    ["dwie"] = 2,
    ["dwoje"] = 2,
    ["dwaj"] = 2,
    ["dwoch"] = 2,
    ["trzy"] = 3,
    ["troje"] = 3,
    ["trzej"] = 3,
    ["trzech"] = 3,
    ["cztery"] = 4,
    ["czworo"] = 4,
    ["czterech"] = 4,
    ["czterej"] = 4,
    ["piec"] = 5,
    ["piecioro"] = 5,
    ["szesc"] = 6,
    ["szescioro"] = 6,
    ["siedem"] = 7,
    ["siedmioro"] = 7,
    ["osiem"] = 8,
    ["osmioro"] = 8,
    ["dziewiec"] = 9,
    ["dziewiecioro"] = 9,
    ["dziesiec"] = 10,
    ["jedenascie"] = 11,
    ["dwanascie"] = 12,
    ["trzynascie"] = 13,
    ["czternascie"] = 14,
    ["pietnascie"] = 15,
    ["szesnascie"] = 16,
    ["siedemnascie"] = 17,
    ["osiemnascie"] = 18,
    ["dziewietnascie"] = 19,
    ["dwadziescia"] = 20,
    ["dwadziescia jeden"] = 21,
    ["dwadziescia dwa"] = 22,
    ["dwadziescia trzy"] = 23,
    ["dwadziescia cztery"] = 24,
    ["dwadziescia piec"] = 25,
    ["dwadziescia szesc"] = 26,
    ["dwadziescia siedem"] = 27,
    ["dwadziescia osiem"] = 28,
    ["dwadziescia dziewiec"] = 29,
    ["trzydziesci"] = 30,
    ["trzydziesci jeden"] = 31,
    ["trzydziesci dwa"] = 32,
    ["trzydziesci trzy"] = 33,
    ["trzydziesci cztery"] = 34,
    ["trzydziesci piec"] = 35,
    ["trzydziesci szesc"] = 36,
    ["trzydziesci siedem"] = 37,
    ["trzydziesci osiem"] = 38,
    ["trzydziesci dziewiec"] = 39,
    ["czterdziesci"] = 40,
}

scripts["tcolor_color"] = "orange"

function scripts:check_gmcp(silent)
    if not next(gmcp) then
        if not silent then
            scripts:print_log("Wyglada na to, ze GMCP nie jest wlaczone. Skrypty nie beda dzialac")
        end
        return false
    end
    return true
end

function scripts:get_table_without_first_item(arr)
    if not arr then
        error("Wrong input")
    end

    local items = {}
    for k, v in pairs(arr) do
        if k > 1 then
            table.insert(items, v)
        end
    end

    return items
end



