function amap:print_help()
    cecho("+-------------------------- <green>Arkadia mapper, ver " ..
        string.sub(amap.ver .. "   ", 0, 5) .. "<grey> ---------------------------+\n")
    cecho("|                                                                                |\n")
    cecho("|         <yellow>https://github.com/tjurczyk/arkadia<grey>                                    |\n")
    cecho(
        "|                         <yellow>Chcesz zadotowac? <LawnGreen>Paypal: dzordzyk@gmail.com<grey>           |\n")
    cecho("|                                                                                |\n")
    cecho("|                         -----------------------------                          |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/pobierz_mape<grey> - pbbierze aktualna mape z serwera.                              |\n")
    cecho("| <light_slate_blue>/zaladuj_mape<grey> - zaladuje mape z katalogu profilu.                              |\n")
    cecho("| <light_slate_blue>/zapisz_mape<grey> - zapisze aktualna mape do katalogu profilu.                      |\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>POMOC<grey>                                                                          |\n")
    cecho("| <light_slate_blue>/mapper<grey> - ta pomoc.                                                            |\n")
    cecho("| <light_slate_blue>/mapper_rys<grey> - pomoc do rysowania.                                              |\n")
    cecho("| <light_slate_blue>/mapper_opcje<grey> - pomoc do opcji.                                                |\n")
    cecho("| <light_slate_blue>/mapper_skroty<grey> - pomoc do skrotow.                                             |\n")
    cecho("| <light_slate_blue>/mapper_db<grey> - pomoc do bazy mappera.                                            |\n")
    cecho("|                                                                                |\n")
    cecho("| -----------------------                                                        |\n")
    cecho("| <yellow>OGOLNE<grey>                                                                         |\n")
    cecho("| <light_slate_blue>/mm [draw|follow|off]<grey> - tryb mappera: 'draw' to rysowanie,                     |\n")
    cecho("| 'follow' to sledzenie, 'off' to wylaczone sledzenie.                           |\n")
    cecho("| <light_slate_blue>/lok<grey> - informacja o aktualnej lokacji.                                         |\n")
    cecho(
        "| <light_slate_blue>/lok [id]<grey> - informacja o lokacji o tym <light_slate_blue>id<grey>.                                     |\n")
    cecho("| <light_slate_blue>/zlok<grey> - stara sie zlokalizowac na podstawie GMCP (najwazniejsze trakty,        |\n")
    cecho("| miasta itp. Sa to lokacje, ktore sa widoczne na mapperze w kliencie webowym).  |\n")
    cecho("| <light_slate_blue>/ustaw [numer_lokacji]<grey> - ustawia cie na konkretnej lokacji.                    |\n")
    cecho("| <light_slate_blue>/wodopoj <grey> - ustawia akt. lokacje jako lokacje z piciem (CTRL+n albo '/pij')    |\n")
    cecho("| <light_slate_blue>/brama <grey> - ustawia akt. lokacje jako brame (komenda 'uderz w brame')            |\n")
    cecho("| <light_slate_blue>/brama [komenda]<grey> - ustawia akt. lokacje jako brame (komenda [komenda])         |\n")
    cecho("| <light_slate_blue>/cofnij <grey> - cofa cie na mapperze do ostatniej lokacji                           |\n")
    cecho("| <light_slate_blue>/nastepny_kierunek <grey> - jesli znajdziemy sie z lokacji z dwoma wyjsciami         |\n")
    cecho("| to ten alias bedzie zawieral nastepny kierunek aby isc dalej.                  |\n")
    cecho("| Brane sa wyjscia z GMCP.                                                       |\n")
    cecho("| <light_slate_blue>/zaznaczaj <grey> - wlaczy/wylaczy zaznaczanie lokacji przez ktore przechodzimy.     |\n")
    cecho("| <light_slate_blue>/idz<grey> - jesli weszlismy na lokacje z dwoma wyjsciam (wedlug mappera),           |\n")
    cecho("| to alias ten wykona kierunek aby podazac dalej. Dziala to na podstawie wyjsc   |\n")
    cecho("| wyjsc z mappera Mudletowego, a nie GMCP/Arkadiowej mapy.                       |\n")
    cecho("| <light_slate_blue>/prowadz [id]<grey> - pokazuje na mapie sciezke do lokacji aktualizowana co krok.    |\n")
    cecho("| <light_slate_blue>/prowadz [nazwa_skrotu]<grey> - - pokazuje na mapie sciezke do skrotu.               |\n")
    cecho("| <light_slate_blue>/prowadz- <grey> - wylacza sciezke prowadzaca do lokacji                             |\n")
    cecho("|                                                                                |\n")
    cecho("| -----------------------                                                        |\n")
    cecho("| <yellow>CHODZIK<grey>                                                                        |\n")
    cecho("| <light_slate_blue>/idz [nazwa_skrotu]<grey> - idzie do lokacji [nazwa_skrotu] ('/mapper_skroty').      |\n")
    cecho("| <light_slate_blue>/idz [nazwa_skrotu] [opoz]<grey> - j.w. z danym [opoznieniem].                       |\n")
    cecho(
        "| <light_slate_blue>/idz [id]<grey> - idzie do lokacji z tym <light_slate_blue>id<grey>.                                         |\n")
    cecho("| <light_slate_blue>/idz [id] [opoz]<grey> - j.w. z danym [opoznieniem].                                 |\n")
    cecho("| <light_slate_blue>/stop<grey> - wylacza chodzik.                                                       |\n")
    cecho("| <light_slate_blue>/dalej<grey> - kontynuuje chodzik (przerwany czymkolwiek).                           |\n")
    cecho("| <light_slate_blue>/dalej [opoz]<grey> - kontynuuje chodzik z danym opoznieniem.                        |\n")
    cecho("| <light_slate_blue>/opoz [liczba]<grey> - ustawia opoznienie na taki czas.                              |\n")
    cecho("| <light_slate_blue>/chodzik<grey> - pokaze informacje o chodziku (cel i opoznienie).                    |\n")
    cecho("| <light_slate_blue>/chodzik wlacz<grey> - wlacza chodzik.                                               |\n")
    cecho("| <light_slate_blue>/chodzik wylacz<grey> - wylacza chodzik (nie bedzie mozna go uzyc)                   |\n")
    cecho("| <light_slate_blue>/szybciej<grey> - przyspiesza chodzik.                                               |\n")
    cecho("| <light_slate_blue>/wolniej<grey> - zwalnia chodzik.                                                    |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/sciezka [numer]<grey> - pokaze sciezke do lokacji [numer]                           |\n")
    cecho("| <light_slate_blue>/pokaz_sciezke [numer]<grey> - podswietli sciezke do lokacji na mapie na 2 sekundy.  |\n")
    cecho("|                                                                                |\n")
    cecho("| -----------------------                                                        |\n")
    cecho("| <yellow>BINDY PO/PRZED<grey>                                                                 |\n")
    cecho("| <light_slate_blue>/pre_walk [komendy_oddzielone_#]<grey> - przed kazdym ruchem wykona                  |\n")
    cecho("| te komendy. Musza byc oddzielone '#' (np: /pre_walk sprawdz kierunki#zerknij)  |\n")
    cecho("| <light_slate_blue>/post_walk [komendy_oddzielone_#]<grey> - po kazdym ruchu wykona                     |\n")
    cecho("| te komendy.                                                                    |\n")
    cecho("| <light_slate_blue>/pwalk-<grey> - resetuje pre i post komendy.                                         |\n")
    cecho("|                                                                                |\n")
    cecho("+--------------------------------------------------------------------------------+\n")
end

function amap:print_draw()
    cecho("+-------------------------- <green>Arkadia mapper, ver " ..
        string.sub(amap.ver .. "   ", 0, 5) .. "<grey> ---------------------------+\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Dostepne KOMENDY:<grey>                                                              |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/dodaj_obszar [nazwa]<grey> - dodaj obszar o nazwie.                                 |\n")
    cecho("| <light_slate_blue>/pokaz_obszary<grey> - pokaze obszary.                                               |\n")
    cecho("| <light_slate_blue>/zmien_obszar [nazwa]<grey> - zmienia obszar aktualnej lokacji na [nazwa].           |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/dodaj_lok [kierunek]<grey> - dodaj lokacje i polacz ja w [kierunku].                |\n")
    cecho("| <light_slate_blue>/dodaj_lok [kierunek] [zlokalizowana]<grey> - dodaj lokacje i polacz ja w [kierunku].|\n")
    cecho("| Roznica jest taka, ze zlokalizowana bedzie z podana lokalizacja.               |\n")
    cecho("| Np: '/dodaj_lok u s' - doda lokacje z przejsciem 'up', ktora bedzie na poludniu|\n")
    cecho("| <light_slate_blue>/ex [numer_lokacji] [kierunek]<grey> - dodaj wyjscie z aktualnej lokacji             |\n")
    cecho("| do [numer lokacji] w kierunku [kierunek].                                      |\n")
    cecho("| <light_slate_blue>/exf [z_lokacji_nr] [do_lokacji_nr] [kierunek]<grey> - dodaj wyjscie                 |\n")
    cecho("| [z lokacji nr] [do_lokacji_nr] w kierunku [kierunek].                          |\n")
    cecho("| <light_slate_blue>/usun_stuby<grey> - usuwa stuby z aktualnej lokacji. Przydatne gdy nie chcesz        |\n")
    cecho("| widziec kikutow jak zmieniasz laczenia pomiedzy lokacjami.                     |\n")
    cecho("| <red>UWAGA<grey>: Powyzsze komendy biora skrocone kierunki, czyli 's', 'n' czy 'u'!       |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/spe_lok [kierunek] [specjalne przejscie]<grey> - dodaje lokacje w kierunku          |\n")
    cecho("| [kierunek], na ktora przechodzi sie komenda [specjalne przejscie]              |\n")
    cecho("| przykladowo: '/spe_lok e przejdz przez strumien' stworzy lokacje na wschod (e) |\n")
    cecho("| od aktualnej, na ktora przechodzi sie przejsciem 'przejdz przez strumien'.     |\n")
    cecho("| <light_slate_blue>/spe [numer lokacji] [przejscie]<grey> - tworzy polaczenie z obecnej lokacji         |\n")
    cecho("| do [numer lokacji], do ktorej przechodzi sie [specjalne przejscie].            |\n")
    cecho("| <light_slate_blue>/kolor<grey> - ustawia kolor aktualnej lokacji.                                      |\n")
    cecho("| <light_slate_blue>/pokaz_kolory<grey> - pokaze liste zdefiniowanych kolorow.                           |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/waga [wartosc]<grey> - ustawia wage tego pokoju.                                    |\n")
    cecho(
        "| <light_slate_blue>/waga [wartosc] [lokacja_id]<grey> - ustawia wage lokacje o tym <light_slate_blue>[lokacja_id]<grey>.        |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/kbind [kierunek] [komendy_oddzielone_#]<grey> - Pozwala pod konkretny kierunek      |\n")
    cecho("| zdefiniowac danych zestaw komend, ktory zostanie wykonany po wybraniu tego     |\n")
    cecho("| kierunku. Przykladowo: <light_slate_blue>/kbind w otworz drzwi kluczem#otworz drzwi#w<grey>            |\n")
    cecho("| sprawi, ze po wykonaniu 'w' na tej lokacji, zostana wykonane najpierw          |\n")
    cecho("| 'otworz drzwi kluczem', nastepnie 'otworz drzwi' i 'w'.                        |\n")
    cecho("| <red>UWAGA<grey>: W zestawie komend do danego kierunku MUSI znalezc sie ten kierunek      |\n")
    cecho("| (czyli w przykladzie 'w'), w przeciwnym razie kierunek nie zostanie wykonany.  |\n")
    cecho("| <light_slate_blue>/kbind_reset<grey> - Zresetuje kbindy na aktualnej lokacji                           |\n")
    cecho("|                                                                                |\n")
    cecho("|                                                                                |\n")
    cecho("+--------------------------------------------------------------------------------+\n")
end

function amap:print_options()
    cecho("+-------------------------- <green>Arkadia mapper, ver " ..
        string.sub(amap.ver .. "   ", 0, 5) .. "<grey> ---------------------------+\n")
    cecho("|                                                                                |\n")
    cecho("| Ustawianie opcji poprzez <light_slate_blue>/ustaw_opcje [nazwa_opcji] [wartosc]<grey>.                 |\n")
    cecho("| Przykladowo: '/ustaw_opcje laczenie_stubow 1'                                  |\n")
    cecho("| Aktualne ustawienie: uzyj '/pokaz_opcje'                                       |\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Dostepne OPCJE:<grey>                                                                |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>skok_x<grey> - ustawia domyslna wartosc skokowa na mapie podczas rysowania 'manual'. |\n")
    cecho("| Czyli jak ruch jest na wschod to 'x' zostanie przesuniete o ta wartosc.        |\n")
    cecho("| Przykladowo dla wartosci '2': (x: 50, y: 60 --> x: 52, y: 60).                 |\n")
    cecho("| <yellow_green>Dostepne wartosci<grey>: jakikolwiek int, sugerowane '2'.                            |\n")
    cecho("| <yellow_green>Domyslne wartosci<grey>: 2.                                                          |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>skok_y<grey> - j.w. ale dla osi y.                                                   |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>laczenie_stubow<grey> - Czy laczyc automatycznie stuby.                              |\n")
    cecho("| Czyli jesli istnieje stub na aktualnie tworzonej lokacji w kierunku lokacji,   |\n")
    cecho("| ktora ma stub w kierunku tworzonej lokacji to je polaczy.                      |\n")
    cecho("| <yellow_green>Dostepne wartosci<grey>:                                                             |\n")
    cecho("| 0 - wylaczone, nic nie bedzie laczone i wszystko trzeba przejsc zeby polaczyc. |\n")
    cecho("| 1 - wlaczone, aktualnie tworzona lokacja polaczy stuby z sasiadami.            |\n")
    cecho("| 2 - to co wyzej + sprawdzi tez sasiadow stuby, czyli mapowanie duzych terenow  |\n")
    cecho("| (jak pustki) bedzie znacznie szybsze.                                          |\n")
    cecho("| <yellow_green>Domyslna wartosc<grey>: 2.                                                           |\n")
    cecho("+--------------------------------------------------------------------------------+\n")
end

function amap:print_shortcuts()
    cecho("+-------------------------- <green>Arkadia mapper, ver " ..
        string.sub(amap.ver .. "   ", 0, 5) .. "<grey> ---------------------------+\n")
    cecho("|                                                                                |\n")
    cecho("| <yellow>Dostepne KOMENDY:<grey>                                                              |\n")
    cecho("|                                                                                |\n")
    cecho("| <light_slate_blue>/dodaj_skrot [id_pokoju] [nazwa] [opis]<grey> - dodaj skrot do [id_pokoju],          |\n")
    cecho("| ktory bedzie mial [nazwe] i daj do niego [opis]. Id to liczba i musi byc       |\n")
    cecho("| taki pokoj w mapperze! Nazwa to krotka nazwa, po ktorej bedziesz go uzywal     |\n")
    cecho("| i musi byc zlozona tylko z malych i duzych liter oraz dozwolony jest '_'.      |\n")
    cecho("| Opis dowolny.                                                                  |\n")
    cecho("| <light_slate_blue>/usun_skrot [nazwa] [nazwa] [opis]<grey> - Usun skrot o [nazwie].                    |\n")
    cecho("| <light_slate_blue>/usun_skroty<grey> - Usun wszystkie skroty.                                          |\n")
    cecho("| <light_slate_blue>/pokaz_skroty<grey> - Pokaze zdefiniowane skroty.                                    |\n")
    cecho("|                                                                                |\n")
    cecho("+--------------------------------------------------------------------------------+\n")
end
