name: Verify config.md, events.md and requires

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run config verification
        run: python ./.github/workflows/check_config.py
      - name: Run events verification
        run: python ./.github/workflows/check_events.py
      - name: Run requires verification
        run: python ./.github/workflows/check_require.py